### ISSUE TITLE
Flexible crop area problem

### ISSUE THREAD

**Issue by Yigityakut** [sergioutama/react-native-image-crop-picker#1]
@sergioutama You said that in your repo it's supported rectangular  (flexible crop area) in this pull request. https://github.com/ivpusic/react-native-image-crop-picker/pull/947

Is it possible to support it without using ` freeStyleCropEnabled: true` ? 

I couldn't see any difference between yours and the original one.

**Comment by sergioutama** [comment]
@Yigityakut I haven't work on this repo for a long time.
Previously YES. The iOS part doesn't care about `freeStyleCropEnabled` value, it always `true` by default.

However, my recent commit [68b9cf0] change this behavior to be the same as the Android.

You will need to provide `freeStyleCropEnabled: true` else it will lock the crop into the aspect ratio specified by your `width` and `height` value.

**Comment by sergioutama** [comment]
@Yigityakut my fork already merged to the main repo. The `freeStyleCropEnabled` is available
